---
- name: test slicing and fork
  hosts: all
  strategy: host_pinned
  serial: 1
  gather_facts: no

  tasks:
    - name: print pre-task
      ansible.builtin.debug:
        msg: "Pre-task"
    
    - name: Pause for 10 sec
      wait_for:
        timeout: 10
      delegate_to: localhost
    
    - name: Print post-task
      ansible.builtin.debug:
        msg: "Post-task"