---
- name: cli parse example
  hosts: cisco
  gather_facts: false

  tasks:
    - name: Run command and parse with native
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          name: ansible.netcommon.native
          template_path: "{{ playbook_dir }}/templates/ios_show_interface.yaml"
        set_fact: interfaces_fact

    - name: Custom facts3
      set_fact:
        custom_fact3: "{{ interfaces_fact }}"
        cacheable: yes

    - name: show facts
      debug:
        msg: "{{ interfaces_fact }}"
