---
- name: cli parse example
  hosts: cisco
  gather_facts: false

  tasks:
    - name: Run command and parse with native
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          name: ansible.netcommon.native
        set_fact: interfaces_fact
