---
- name: Compare Startup to Running config
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:

  tasks:
    - name: check the startup-config against the running-config
      ios_config:
        diff_against: running
        diff_ignore_lines:
        - ntp clock .*
