---
- name: Compliance Check NETWORK TIME
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    ntp_server: "216.239.35.12"

  tasks:
    - name: CONFIGURE NTP
      ios_config:
        lines: "ntp server {{ntp_server}}"
