---
- name: CONFIGURE NETWORK Name Server
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    dns_server: "8.8.8.8"

  tasks:
    - name: CONFIGURE NTP
      ios_config:
        lines: "ip  name-server {{dns_server}}"
