---
- name: Conditional Network Demo
  hosts: cisco
  connection: network_cli
  gather_facts: no

  vars:
    ntp_server: "216.239.35.0"
    ntp_server_fail: "300.300.300.300"
  tasks:
    - name: ipv4 success
      assert:
        that:
          - "ntp_server | ipaddr"
        success_msg: "'This is a valid IPv4 address"

    - name: ipv4 fail
      assert:
        that:
          - "ntp_server_fail | ipaddr"
        msg: "This is NOT a valid IPv4 address"
