---
- name: Conditional Network Demo
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    - name: check for IOS in show version
      cisco.ios.command:
        commands: show version
        wait_for: result[0] contains IOS

  

