---
- name: gather information from routers
  hosts: cisco
  gather_facts: false

  tasks:
    - name: display fact cache
      debug:
        msg:
          - "IOS Serial number : {{ ansible_net_serialnum }}"
          - "The IOS version: {{ ansible_net_version }}"
