---
- name: gather information from routers
  hosts: cisco
  gather_facts: true
  vars:
    var_fact: Joon_Var_fact2

  tasks:
    - name: display interfaces
      debug:
        msg: "The IOS Interfaces: {{ ansible_net_interfaces }}"

    - name: Custom facts
      set_fact:
        custom_fact1: Joon_fact1
        custom_fact2: "{{ var_fact }}"
        cacheable: yes
