---
- name: gather information from routers
  hosts: cisco
  gather_facts: false

  tasks:
    - name: gather router facts
      ios_facts:
        gather_subset: min
        gather_network_resources: interfaces
      register: output

    - name: display interfaces
      debug:
        msg: "The IOS Interfaces: {{ output.ansible_facts.ansible_network_resources.interfaces.['"name"'] }}"
