---
- name: gather information from routers
  hosts: cisco
  gather_facts: true
  vars:
    var_fact: Joon_Var_fact2

  tasks:

    - name: display ios
      debug:
        msg: "IOS version {{ ansible_net_version }}"

    - name: Custom facts
      set_fact:
        custom_fact1: Joon_fact1
        custom_fact2: "{{ var_fact }}"
        cacheable: yes
