---
- name: gather information from routers
  hosts: cisco
  gather_facts: false
  vars:
    var_fact: Joon_Var_fact2

  tasks:
    - name: Gather legacy and resource facts
      ios_facts:
        gather_subset: all
        gather_network_resources: all
      register: output

    - name: display ios facts
      debug:
        msg: "{{ output }}"

    - name: Custom facts
      set_fact:
        custom_fact1: Joon_fact1
        custom_fact2: "{{ var_fact }}"
        cacheable: yes
