---
- name: gather information from routers
  hosts: cisco
  gather_facts: false

  tasks:
    - name: gather router facts
      ios_facts:

    - name: display interfaces
      debug:
        msg: "The IOS Interfaces: {{ ansible_net_interfaces[0] }}"
