---
- name: gather information from routers
  hosts: cisco
  gather_facts: true

  tasks:
    - name: display interfaces
      debug:
        msg: "The IOS Interfaces: {{ ansible_net_interfaces }}"

    - name: Custom facts
      set_fact: custom_fact1="Joon_fact1" custom_fact2="Joon_fact2"
