---
- name: Get command_timeout
  hosts: all
  gather_facts: no

  tasks:
    - name: Get command_timeout
      debug:
        msg: "This is command timeout value {{ ANSIBLE_PERSISTENT_COMMAND_TIMEOUT }}"
