---
- name: gather information from routers
  hosts: cisco
  gather_facts: false

  tasks:
    - name: gather router facts
      ios_facts:
        gather_subset: all
      register: output

    - name: display interfaces
      debug:
        msg: "Output {{ output }}"
