---
- name: IP extended ACL addition
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    acl_name: test
    insert_num: 15
    acl_config: "permit ip host 192.0.3.3 any log"

  tasks:
    - name: Add IP ACL extended
      cisco.ios.ios_config:
        lines:
          - "{{ insert_num }} {{ acl_config }}"
        parents: "ip access-list extended {{ acl_name }}"

    - name: Resquence IP ACL extended
      cisco.ios.ios_config:
        lines:
          - "ip access-list resequence {{ acl_name }} 10 10"

    - name: Check IP ACL list outcome
      cisco.ios.ios_command:
        commands:
          - "show ip access-list {{ acl_name }}"
      register: output

    - name: Output acl results
      debug:
        msg: "{{ output }}"
