---
- name: Network Interface List
  hosts: all
  gather_facts: yes

  tasks:

    - name: List ALL Interfaces
      debug:
        msg: "{{ item.key }}"
      with_dict: "{{ ansible_net_interfaces }}"
