---
- name: Shutdown Loopback440 Interface on NX-OS
  hosts: nxos_switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Ensure Loopback440 is administratively up
      cisco.nxos.nxos_interfaces:
        config:
          - name: Loopback440
            enabled: true
        state: merged