---
- name: Disable OSPF Max Metric
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    ospf_id: 1

  tasks:
    - name: Remove ospf max metric
      cisco.ios.ios_config:
        lines:
          - "no max-metric router-lsa"
        parents: "router ospf {{ ospf_id}}"
