---
- name: configure IOS interface Merge
  hosts: rtr1
  gather_facts: false

  tasks:
  - name: Merge provided configuration with device configuration
    cisco.ios.interfaces:
      config: "{{ interfaces }}"
      state: merged
