---
    - name: Rendered Interface
      hosts: cisco
      gather_facts: false
  
      tasks:
      - name: use Interface resource module
        cisco.ios.interfaces:
          state: rendered
        register: interface_config
  
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: /resource/
          state: directory
        delegate_to: backup-server
        become: true
        run_once: true
  
      - name: copy interface_config to file
        copy:
          content: "{{ interface_config | to_nice_yaml }}"
          dest: "/resource/{{ inventory_hostname }}_interface_rendered.yml"
        become: true
        delegate_to: backup-server
  