---
- name: rendered ACLs
  hosts: arista
  gather_facts: false

  tasks:
  - name: rendered provided configuration with device configuration
    arista.eos.eos_acls:
      config:
      - afi: ipv4
        acls:
        - name: test1
          aces:
          - sequence: 35
            grant: deny
            protocol: ospf
            source:
              subnet_address: 20.0.0.0/8
            destination:
              any: true
      state: rendered
