---
  - name: Gather ACL
    hosts: cisco
    gather_facts: false

    tasks:

    - name: use vlans resource module
      cisco.ios.ios_acls:
        state: gathered
      register: acl_config

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /resource/
        state: directory
      delegate_to: backup-server
      become: true
      run_once: true

    - name: copy vlan_config to file
      copy:
        content: "{{ acl_config | to_nice_yaml }}"
        dest: "/resource/{{ inventory_hostname }}_acl.yml"
      become: true
      delegate_to: backup-server
