---
- name: configure IOS ACLs replaced
  hosts: rtr1
  gather_facts: false

  tasks:
  - name: replaced provided configuration with device configuration
    cisco.ios.ios_acls:
      config: "{{ acls_demo }}"
      state: replaced
