---
- name: Configure CDP
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    cdp_interface: GigabitEthernet1

  tasks:
    - name: Configure Global CDP
      ios_config:
        lines: "cdp run"

    - name: Configure CDP on Interfaces
      ios_config:
        lines:
          - "cdp enable"
          - "description CDP_enabled_by_Ansible_Self_healing_demo"
        parents: "interface {{ cdp_interface }}"
