---
- name: Enable Flapping Interface
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    flap_interface: Loopback10
    int_desc: "Configured and Merged by Ansible Automation for Self Healing Demo"
    
  tasks:
    - name: Enable flapping interface
      ios_interfaces:
        config:
          - name: "{{ flap_interface }}"
            description: "{{ int_desc }}"
            enabled: True
        state: replaced
