---
- name: Enable Flapping Interface
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    flap_interface: Loopback10

  tasks:
    - name: Enable flapping interface
      ios_interfaces:
        config:
          - name: "{{ flap_interface }}"
            description: 'Configured and Merged by Ansible Automation for Self Healing Demo'
            enabled: True
        state: merged
