---
- name: Shutdown Flapping Interface
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    flap_interface: Loopback10

  tasks:
    - name: Shutdown flapping interface
      ios_interfaces:
        config:
          - name: "{{ flap_interface }}"
            description: 'Shutdown by Ansible Automation for Self Healing Demo'
            enabled: False
        state: merged
