---
- name: Shutdown Flapping Interface
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Shutdown flapping interface
      ios_interfaces:
        config:
          - name: Loopback10
            description: 'Configured and Merged by Ansible for Self Healing Demo'
            enabled: False
        state: merged
