---
- hosts: all
  gather_facts: False
  vars:
    testvar: "success"
  tasks:
    - name: Start WAS
      debug:
        msg: "Starting WAS for {{ inventory_hostname }}"
      tags:
        - wasstart

    - name: Stop WAS
      debug:
        msg: "Stopping WAS for {{ inventory_hostname }}"
      tags:
        - wasstop

    - name: Restart WAS
      debug:
        msg: "Restart WAS for {{ inventory_hostname }}"
      tags:
        - wasrestart

    - name: block tag demo
      block:
        - name: 1st task in block 
          debug: 
            msg: "1st Task in Block"
          tags: blocktask1
        
        - name: 2nd task in block
          debug:
            msg: "2nd Task in Block"
          tags: blocktask2

    - name: block tag always         
      block:
        - name: 1st task in always block 
          assert:
            that:
              - testvar == "success"
            success_msg: "success"
            fail_msg: "failed"
          register: result
          tags: always
        
        - name: 2nd task in always block
          debug:
            msg: "2nd Task in Always Block"
          when: result.failed == True
          tags: ["never", "alwaysblocktask2"]