---
- hosts: all
  gather_facts: False
  tasks:

    - name: Start WAS
      debug:
        msg: "Starting WAS for {{ ansible_hostname }}"
      tags:
        - wasstart

    - name: Stop WAS
      debug:
        msg: "Stopping WAS for {{ ansible_hostname }}"
      tags:
        - wasstop

    - name: Restart WAS
      debug:
        msg: "Restart WAS for {{ ansible_hostname }}"
      tags:
        - wasrestart
