---
- name: test slicing and fork
  hosts: all
  gather_facts: no

  tasks:
    - name: print pre-task
      ansible.builtin.debug:
        msg: "Pre-task"
    
    - name: Pause
      ansible.builtin.pause:
        seconds: 10
    
    - name: Print post-task
      ansible.builtin.debug:
        msg: "Post-task"