interface: Loopback10
ip: 192.168.210.1 255.255.255.255
desc_int: This is example from host_vars rtr1 ios in master branch
interfaces:
  - enabled: true
    name: loopback100
    description: Source_Of_Truth_JP_Demo
vlans:
  - name: Source-of_Truth_111
    vlan_id: 111
acls_demo:
  - afi: ipv4
    acls:
    - name: 110
      aces:
      - grant: deny
        sequence: 20
        protocol_options:
          tcp:
            ack: true
        source:
          address: 198.51.100.0
          wildcard_bits: 0.0.0.255
          port_protocol:
            eq: telnet
        destination:
          address: 198.51.110.0
          wildcard_bits: 0.0.0.255
          port_protocol:
            eq: www
        dscp: ef
        ttl:
          eq: 10
