interface: Loopback10
ip: 192.168.210.1 255.255.255.255
desc_int: This is example from host_vars rtr1 ios in master branch
interfaces:
  - enabled: true
    name: loopback100
    description: Source_Of_Truth_JP_Demo
vlans:
  - name: Source-of_Truth_111
    vlan_id: 111
acls_demo:
  - afi: ipv4
    acls:
    - name: sot_acl
      aces:
      - sequence: 35
        grant: deny
        protocol: ospf
        source:
          subnet_address: 20.0.0.0/8
        destination:
          any: true
