---
authors:
  - Sean Sullivan @sean-m-sullivan
dependencies: {}
description: Ansible content that interacts with the Ansible Automation Hub or Galaxy NG API.
documentation: https://github.com/redhat-cop/ah_configuration/blob/master/README.md
issues: https://github.com/redhat-cop/ah_configuration/issues
license:
  - GPL-3.0-only
name: ah_configuration
namespace: redhat_cop
readme: README.md
repository: https://github.com/redhat-cop/ah_configuration
tags:
  - cloud
  - infrastructure
  - galaxy
  - ansible
  - galaxy
  - automation
version: 0.0.1-devel
build_ignore:
  - tools
  - setup.cfg
  - galaxy.yml.j2
  - template_galaxy.yml
  - '*.tar.gz'
...
