---
# Create AH repository
- name: Update Certified repository
  ah_repository:
    name:                 "rh-certified"
    url:                  "{{ ah_repository_certified['url'] | default('https://cloud.redhat.com/api/automation-hub/') }}"
    auth_url:             "{{ ah_repository_certified['auth_url'] | default('https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token') }}"
    token:                "{{ ah_repository_certified['token'] | default(omit) }}"
    username:             "{{ ah_repository_certified['username'] | default(omit) }}"
    password:             "{{ ah_repository_certified['password'] | default(omit) }}"
    download_concurrency: "{{ ah_repository_certified['download_concurrency'] | default(10) }}"
    rate_limit:           "{{ ah_repository_certified['rate_limit'] | default(8) }}"
    signed_only:          "{{ ah_repository_certified['signed_only'] | default(false) }}"
    tls_validation:       "{{ ah_repository_certified['tls_validation'] | default(true) }}"
    client_key:           "{{ ah_repository_certified['client_key'] | default(omit) }}"
    client_cert:          "{{ ah_repository_certified['client_cert'] | default(omit) }}"
    ca_cert:              "{{ ah_repository_certified['ca_cert'] | default(omit) }}"
    client_key_path:      "{{ ah_repository_certified['client_key_path'] | default(omit) }}"
    client_cert_path:     "{{ ah_repository_certified['client_cert_path'] | default(omit) }}"
    ca_cert_path:         "{{ ah_repository_certified['ca_cert_path'] | default(omit) }}"
    proxy_url:            "{{ proxy_url | default(omit) }}"
    proxy_username:       "{{ proxy_username | default(omit) }}"
    proxy_password:       "{{ proxy_password | default(omit) }}"
    ah_host:              "{{ ah_host | default(ah_hostname) }}"
    ah_username:          "{{ ah_username | default(omit) }}"
    ah_password:          "{{ ah_password | default(omit) }}"
    ah_token:             "{{ ah_token | default(omit) }}"
    ah_path_prefix:       "{{ ah_path_prefix | default(omit) }}"
    validate_certs:       "{{ ah_validate_certs | default(omit) }}"
  no_log: "{{ ah_configuration_repository_secure_logging }}"
  when: ah_repository_certified is defined

- name: Update Community repository
  ah_repository:
    name:                 "community"
    url:                  "{{ ah_repository_community['url'] | default('https://galaxy.ansible.com/api/') }}"
    username:             "{{ ah_repository_community['username'] | default(omit) }}"
    password:             "{{ ah_repository_community['password'] | default(omit) }}"
    requirements:         "{{ ah_repository_community['requirements'] | default(omit) }}"
    requirements_file:    "{{ ah_repository_community['requirements_file'] | default(omit) }}"
    download_concurrency: "{{ ah_repository_community['download_concurrency'] | default(10) }}"
    rate_limit:           "{{ ah_repository_community['rate_limit'] | default(8) }}"
    signed_only:          "{{ ah_repository_community['signed_only'] | default(omit) }}"
    tls_validation:       "{{ ah_repository_community['tls_validation'] | default(true) }}"
    client_key:           "{{ ah_repository_community['client_key'] | default(omit) }}"
    client_cert:          "{{ ah_repository_community['client_cert'] | default(omit) }}"
    ca_cert:              "{{ ah_repository_community['ca_cert'] | default(omit) }}"
    client_key_path:      "{{ ah_repository_community['client_key_path'] | default(omit) }}"
    client_cert_path:     "{{ ah_repository_community['client_cert_path'] | default(omit) }}"
    ca_cert_path:         "{{ ah_repository_community['ca_cert_path'] | default(omit) }}"
    proxy_url:            "{{ proxy_url | default(omit) }}"
    proxy_username:       "{{ proxy_username | default(omit) }}"
    proxy_password:       "{{ proxy_password | default(omit) }}"
    ah_host:              "{{ ah_host | default(ah_hostname) }}"
    ah_username:          "{{ ah_username | default(omit) }}"
    ah_password:          "{{ ah_password | default(omit) }}"
    ah_path_prefix:       "{{ ah_path_prefix | default(omit) }}"
    validate_certs:       "{{ ah_validate_certs | default(omit) }}"
  no_log: "{{ ah_configuration_repository_secure_logging }}"
  when: ah_repository_community is defined
...
