---
- name: Include vars
  ansible.builtin.include_vars: ../vars/ah_ee_repository_sync.yml
  tags:
    - reposync

- name: Import ah_configuration role
  ansible.builtin.import_role:
    name: redhat_cop.ah_configuration.ee_repository_sync
  tags:
    - reposync
...
