---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yml for what hooks are executed
name: Yaml and Ansible Lint

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Pre-reqs
        # cp is to make ansible-lint into thinking that awx.awx plugins are part of the collection so it lints properly.
        run: |
          sudo apt install software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          pip install --upgrade ansible
          cp .github/workflow-config/galaxy.yml galaxy.yml
          ansible-config view -vvv
  #        ansible-galaxy collection build
  #        ansible-galaxy collection install *.tar.gz -f
      - uses: pre-commit/action@v2.0.3
...
