---
- name: Playbook to configure Private Automation Hub
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration

  vars:
    target_state: "present"

  pre_tasks:
    - name: Include Vars
      include_vars: vars/pah_vars.yml
      tags:
        - always

  tasks:
    - name: Include task to manage private automation hub groups
      include_tasks: tasks/manage_groups.yml
      tags:
        - groups

    - name: Include task to manage private automation hub users
      include_tasks: tasks/manage_users.yml
      tags:
        - users

    # All tasks below here may need to be re-ordered so they
    # execute in a particular order.
    - name: Include task for managing collection namespaces
      include_tasks: tasks/manage_collection_namespaces.yml
      tags:
        - namespaces

    - name: Include task for collection publishing
      include_tasks: tasks/manage_collection_publish.yml
      tags:
        - publish

    - name: Include task for execution environment images
      include_tasks: tasks/manage_ee_images.yml
      tags:
        - ee_images

    - name: Include task to manage execution enviornment namespaces
      include_tasks: tasks/manage_ee_namespaces.yml
      tags:
        - ee_namespaces

    - name: Include task to manage execution environment registries
      include_tasks: tasks/manage_ee_registries.yml
      tags:
        - registries

    - name: Include task to manage execution environment registry indices
      include_tasks: tasks/manage_ee_registry_indices.yml
      tags:
        - indices

    - name: Include task to manage execution environment registry sync
      include_tasks: tasks/manage_ee_registry_sync.yml
      tags:
        - regsync

    - name: Include task to manage execution environment repositories
      include_tasks: tasks/manage_ee_repositories.yml
      tags:
        - repos

    - name: Include task to manage execution environment repository sync
      include_tasks: tasks/manage_ee_repository_sync.yml
      tags:
        - reposync
...
